/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of BCM2835.xs. Do not edit this file, edit BCM2835.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

///////////////////////////////////////////////////////////////////////////////////////
// File          bcm2835/BCM2385.xs
// Description:  XS module for HiPi::Device::BCM2385
// Created       Fri Nov 23 12:13:43 2012
// SVN Id        $Id:$
// Copyright:    Copyright (c) 2012 Mark Dootson
// Licence:      This work is free software; you can redistribute it and/or modify it 
//               under the terms of the GNU General Public License as published by the 
//               Free Software Foundation; either version 2 of the License, or any later 
//               version.
///////////////////////////////////////////////////////////////////////////////////////

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "mylib/include/ppport.h"
#define BCM2835_NO_DELAY_COMPATIBILITY
#include "BCM2835/src/src/bcm2835.h"

#define XSRPI_INT_FALL    0x01
#define XSRPI_INT_RISE    0x02
#define XSRPI_INT_AFALL   0x04
#define XSRPI_INT_ARISE   0x08
#define XSRPI_INT_HIGH    0x10
#define XSRPI_INT_LOW     0x20

/*----------------------------------------------------------------
 * C CODE SECTION
 *
 * why replace base bcm2835 sections?
 * because I wanted to be able to specify
 * different BSC peripherals for I2C
 *----------------------------------------------------------------*/

void hipi_i2c_setSlaveAddress(volatile uint32_t* baseaddress, uint8_t addr );
void hipi_i2c_setClockDivider( volatile uint32_t* baseaddress, uint16_t divider );
uint8_t hipi_i2c_write( volatile uint32_t* baseaddress, const char * buf, uint32_t len );
uint8_t hipi_i2c_read( volatile uint32_t* baseaddress, char* buf, uint32_t len );
uint8_t hipi_i2c_read_register_rs( volatile uint32_t* baseaddress, char* regaddr, char* readbuf, uint32_t len );

void hipi_i2c_setSlaveAddress(volatile uint32_t* baseaddress, uint8_t addr )
{
   	volatile uint32_t* paddr = baseaddress + BCM2835_BSC_A/4;
	bcm2835_peri_write(paddr, addr);
}

void hipi_i2c_setClockDivider( volatile uint32_t* baseaddress, uint16_t divider )
{
    volatile uint32_t* paddr = baseaddress + BCM2835_BSC_DIV/4;
    bcm2835_peri_write(paddr, divider);
}

uint8_t hipi_i2c_write( volatile uint32_t* baseaddress, const char* buf, uint32_t len )
{
    volatile uint32_t* dlen    = baseaddress + BCM2835_BSC_DLEN/4;
    volatile uint32_t* fifo    = baseaddress + BCM2835_BSC_FIFO/4;
    volatile uint32_t* status  = baseaddress + BCM2835_BSC_S/4;
    volatile uint32_t* control = baseaddress + BCM2835_BSC_C/4;
    volatile uint32_t* divaddr = baseaddress + BCM2835_BSC_DIV/4;
    
    uint16_t divider = bcm2835_peri_read(divaddr);
    int i2c_byte_wait_us = ((float)divider / BCM2835_CORE_CLK_HZ) * 1000000 * 9;

    uint32_t remaining = len;
    uint32_t i = 0;
    uint8_t reason = BCM2835_I2C_REASON_OK;

    // Clear FIFO
    bcm2835_peri_set_bits(control, BCM2835_BSC_C_CLEAR_1 , BCM2835_BSC_C_CLEAR_1 );
    // Clear Status
	bcm2835_peri_write_nb(status, BCM2835_BSC_S_CLKT | BCM2835_BSC_S_ERR | BCM2835_BSC_S_DONE);
	// Set Data Length
    bcm2835_peri_write_nb(dlen, len);
    // pre populate FIFO with max buffer
    while( remaining && ( i < BCM2835_BSC_FIFO_SIZE ) )
    {
        bcm2835_peri_write_nb(fifo, buf[i]);
        i++;
        remaining--;
    }
    
    // Enable device and start transfer
    bcm2835_peri_write_nb(control, BCM2835_BSC_C_I2CEN | BCM2835_BSC_C_ST);
    
    // Transfer is over when BCM2835_BSC_S_DONE
    while(!(bcm2835_peri_read_nb(status) & BCM2835_BSC_S_DONE ))
    {
        while ( remaining && (bcm2835_peri_read_nb(status) & BCM2835_BSC_S_TXD ))
        {
            // Write to FIFO, no barrier
            bcm2835_peri_write_nb(fifo, buf[i]);
            i++;
            remaining--;
        }
    }
    
    // Received a NACK
    if (bcm2835_peri_read(status) & BCM2835_BSC_S_ERR)
    {
		reason = BCM2835_I2C_REASON_ERROR_NACK;
    }

    // Received Clock Stretch Timeout
    else if (bcm2835_peri_read(status) & BCM2835_BSC_S_CLKT)
    {
		reason = BCM2835_I2C_REASON_ERROR_CLKT;
    }

    // Not all data is sent
    else if (remaining)
    {
		reason = BCM2835_I2C_REASON_ERROR_DATA;
    }

    bcm2835_peri_set_bits(control, BCM2835_BSC_S_DONE , BCM2835_BSC_S_DONE);

    return reason;
}


uint8_t hipi_i2c_read( volatile uint32_t* baseaddress, char* buf, uint32_t len )
{
    volatile uint32_t* dlen    = baseaddress + BCM2835_BSC_DLEN/4;
    volatile uint32_t* fifo    = baseaddress + BCM2835_BSC_FIFO/4;
    volatile uint32_t* status  = baseaddress + BCM2835_BSC_S/4;
    volatile uint32_t* control = baseaddress + BCM2835_BSC_C/4;
    volatile uint32_t* divaddr = baseaddress + BCM2835_BSC_DIV/4;
    
    uint16_t divider = bcm2835_peri_read(divaddr);
    int i2c_byte_wait_us = ((float)divider / BCM2835_CORE_CLK_HZ) * 1000000 * 9;

    uint32_t remaining = len;
    uint32_t i = 0;
    uint8_t reason = BCM2835_I2C_REASON_OK;
    
    // Clear FIFO
    bcm2835_peri_set_bits(control, BCM2835_BSC_C_CLEAR_1 , BCM2835_BSC_C_CLEAR_1 );
    // Clear Status
	bcm2835_peri_write_nb(status, BCM2835_BSC_S_CLKT | BCM2835_BSC_S_ERR | BCM2835_BSC_S_DONE);
	// Set Data Length
    bcm2835_peri_write_nb(dlen, len);
    // Start read
    bcm2835_peri_write_nb(control, BCM2835_BSC_C_I2CEN | BCM2835_BSC_C_ST | BCM2835_BSC_C_READ);
    
    // wait for transfer to complete
    while (!(bcm2835_peri_read_nb(status) & BCM2835_BSC_S_DONE))
    {
        // we must empty the FIFO as it is populated and not use any delay
        while (bcm2835_peri_read_nb(status) & BCM2835_BSC_S_RXD)
        {
            // Read from FIFO, no barrier
            buf[i] = bcm2835_peri_read_nb(fifo);
            i++;
            remaining--;
        }
    }
    
    // transfer has finished - grab any remaining stuff in FIFO
    while (remaining && (bcm2835_peri_read_nb(status) & BCM2835_BSC_S_RXD))
    {
        // Read from FIFO, no barrier
        buf[i] = bcm2835_peri_read_nb(fifo);
        i++;
        remaining--;
    }
    
    // Received a NACK
    if (bcm2835_peri_read(status) & BCM2835_BSC_S_ERR)
    {
		reason = BCM2835_I2C_REASON_ERROR_NACK;
    }

    // Received Clock Stretch Timeout
    else if (bcm2835_peri_read(status) & BCM2835_BSC_S_CLKT)
    {
		reason = BCM2835_I2C_REASON_ERROR_CLKT;
    }

    // Not all data is received
    else if (remaining)
    {
		reason = BCM2835_I2C_REASON_ERROR_DATA;
    }

    bcm2835_peri_set_bits(control, BCM2835_BSC_S_DONE , BCM2835_BSC_S_DONE);

    return reason;
}


uint8_t hipi_i2c_read_register_rs( volatile uint32_t* baseaddress, char* regaddr, char* buf, uint32_t len )
{   
    volatile uint32_t* dlen    = baseaddress + BCM2835_BSC_DLEN/4;
    volatile uint32_t* fifo    = baseaddress + BCM2835_BSC_FIFO/4;
    volatile uint32_t* status  = baseaddress + BCM2835_BSC_S/4;
    volatile uint32_t* control = baseaddress + BCM2835_BSC_C/4;
    volatile uint32_t* divaddr = baseaddress + BCM2835_BSC_DIV/4;
    
    uint16_t divider = bcm2835_peri_read(divaddr);
    int i2c_byte_wait_us = ((float)divider / BCM2835_CORE_CLK_HZ) * 1000000 * 9;
    int i = 0;
    
    uint32_t remaining = len;
    uint8_t reason = BCM2835_I2C_REASON_OK;
    
    // Clear FIFO
    bcm2835_peri_set_bits(control, BCM2835_BSC_C_CLEAR_1 , BCM2835_BSC_C_CLEAR_1 );
    // Clear Status
	bcm2835_peri_write_nb(status, BCM2835_BSC_S_CLKT | BCM2835_BSC_S_ERR | BCM2835_BSC_S_DONE);
	// Set Data Length
    bcm2835_peri_write_nb(dlen, 1);
    // Enable device and start transfer
    bcm2835_peri_write_nb(control, BCM2835_BSC_C_I2CEN);
    bcm2835_peri_write_nb(fifo, regaddr[0]);
    bcm2835_peri_write_nb(control, BCM2835_BSC_C_I2CEN | BCM2835_BSC_C_ST);
    
    // poll for transfer has started
    while ( !( bcm2835_peri_read_nb(status) & BCM2835_BSC_S_TA ) )
    {
        // Linux may cause us to miss entire transfer stage
        if(bcm2835_peri_read(status) & BCM2835_BSC_S_DONE)
            break;
    }
    
    // Send a start-read
    bcm2835_peri_write_nb(dlen, len);
    bcm2835_peri_write_nb(control, BCM2835_BSC_C_I2CEN | BCM2835_BSC_C_ST  | BCM2835_BSC_C_READ );
    
    // Wait for write to complete and first byte back.
    bcm2835_delayMicroseconds(i2c_byte_wait_us * 3);
    
    // wait for transfer to complete
    while (!(bcm2835_peri_read_nb(status) & BCM2835_BSC_S_DONE))
    {
        // we must empty the FIFO as it is populated and not use any delay
        while (remaining && bcm2835_peri_read_nb(status) & BCM2835_BSC_S_RXD)
        {
            // Read from FIFO, no barrier
            buf[i] = bcm2835_peri_read_nb(fifo);
            i++;
            remaining--;
        }
    }
    
    // transfer has finished - grab any remaining stuff in FIFO
    while (remaining && (bcm2835_peri_read_nb(status) & BCM2835_BSC_S_RXD))
    {
        // Read from FIFO, no barrier
        buf[i] = bcm2835_peri_read_nb(fifo);
        i++;
        remaining--;
    }
    
    // Received a NACK
    if (bcm2835_peri_read(status) & BCM2835_BSC_S_ERR)
    {
		reason = BCM2835_I2C_REASON_ERROR_NACK;
    }

    // Received Clock Stretch Timeout
    else if (bcm2835_peri_read(status) & BCM2835_BSC_S_CLKT)
    {
		reason = BCM2835_I2C_REASON_ERROR_CLKT;
    }

    // Not all data is sent
    else if (remaining)
    {
		reason = BCM2835_I2C_REASON_ERROR_DATA;
    }

    bcm2835_peri_set_bits(control, BCM2835_BSC_S_DONE , BCM2835_BSC_S_DONE);

    return reason;
}


/*----------------------------------------------
 * Perl Section
 *----------------------------------------------*/


#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	uint32_t	RETVAL;
	dXSTARG;
    RETVAL = (uint32_t)bcm2835_gpio;
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_pwm); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_pwm)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	uint32_t	RETVAL;
	dXSTARG;
    RETVAL = (uint32_t)bcm2835_pwm;
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_clk); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_clk)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	uint32_t	RETVAL;
	dXSTARG;
    RETVAL = (uint32_t)bcm2835_clk;
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_pads); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_pads)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	uint32_t	RETVAL;
	dXSTARG;
    RETVAL = (uint32_t)bcm2835_pads;
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi0); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi0)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	uint32_t	RETVAL;
	dXSTARG;
    RETVAL = (uint32_t)bcm2835_spi0;
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_bsc0); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_bsc0)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	uint32_t	RETVAL;
	dXSTARG;
    RETVAL = (uint32_t)bcm2835_bsc0;
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_bsc1); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_bsc1)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	uint32_t	RETVAL;
	dXSTARG;
    RETVAL = (uint32_t)bcm2835_bsc1;
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_st); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_st)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	uint32_t	RETVAL;
	dXSTARG;
    RETVAL = (uint32_t)bcm2835_st;
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_hipi_gpio_fget); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_hipi_gpio_fget)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;
	uint8_t	RETVAL;
	dXSTARG;
    volatile uint32_t* paddr = bcm2835_gpio + BCM2835_GPFSEL0/4 + (pin/10);
    uint8_t  shift  = (pin % 10) * 3;
    uint32_t mask   = BCM2835_GPIO_FSEL_MASK << shift;
    uint32_t result = bcm2835_peri_read(paddr) & mask;
    RETVAL = result >> shift;
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_hipi_gpio_get_eds); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_hipi_gpio_get_eds)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;
	int	RETVAL;
	dXSTARG;
    volatile uint32_t* paddr;
    uint8_t shift;
    uint32_t output;
    uint32_t mask;
    RETVAL = 0;

    /* REN */
    paddr = bcm2835_gpio + BCM2835_GPREN0/4 + pin/32;
    shift = pin % 32;
    mask  = 1 << shift;
    output = bcm2835_peri_read(paddr) & mask;
    if( (output >> shift) == 1 ) {
        RETVAL += XSRPI_INT_RISE;
    }

    /* FEN */
    paddr = bcm2835_gpio + BCM2835_GPFEN0/4 + pin/32;
    shift = pin % 32;
    mask  = 1 << shift;
    output = bcm2835_peri_read(paddr) & mask;
    if( (output >> shift) == 1 ) {
        RETVAL += XSRPI_INT_FALL;
    }

    /* HEN */
    paddr = bcm2835_gpio + BCM2835_GPHEN0/4 + pin/32;
    shift = pin % 32;
    mask  = 1 << shift;
    output = bcm2835_peri_read(paddr) & mask;
    if( (output >> shift) == 1 ) {
        RETVAL += XSRPI_INT_HIGH;
    }

    /* LEN */
    paddr = bcm2835_gpio + BCM2835_GPLEN0/4 + pin/32;
    shift = pin % 32;
    mask  = 1 << shift;
    output = bcm2835_peri_read(paddr) & mask;
    if( (output >> shift) == 1 ) {
        RETVAL += XSRPI_INT_LOW;
    }

    /* AFEN */
    paddr = bcm2835_gpio + BCM2835_GPAFEN0/4 + pin/32;
    shift = pin % 32;
    mask  = 1 << shift;
    output = bcm2835_peri_read(paddr) & mask;
    if( (output >> shift) == 1 ) {
        RETVAL += XSRPI_INT_AFALL;
    }

    /* AREN */
    paddr = bcm2835_gpio + BCM2835_GPAREN0/4 + pin/32;
    shift = pin % 32;
    mask  = 1 << shift;
    output = bcm2835_peri_read(paddr) & mask;
    if( (output >> shift) == 1 ) {
        RETVAL += XSRPI_INT_ARISE;
    }

	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835__hipi_i2c_setSlaveAddress); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835__hipi_i2c_setSlaveAddress)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "baseaddress, addr");
    {
	volatile uint32_t*	baseaddress = INT2PTR(volatile uint32_t *,SvIV(ST(0)))
;
	uint8_t	addr = (uint8_t)SvUV(ST(1))
;
    hipi_i2c_setSlaveAddress( baseaddress, addr );
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835__hipi_i2c_setClockDivider); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835__hipi_i2c_setClockDivider)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "baseaddress, divider");
    {
	volatile uint32_t*	baseaddress = INT2PTR(volatile uint32_t *,SvIV(ST(0)))
;
	uint16_t	divider = (uint16_t)SvUV(ST(1))
;
    hipi_i2c_setClockDivider( baseaddress, divider );
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835__hipi_i2c_set_transfer_params); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835__hipi_i2c_set_transfer_params)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "baseaddress, addr, divider");
    {
	volatile uint32_t*	baseaddress = INT2PTR(volatile uint32_t *,SvIV(ST(0)))
;
	uint8_t	addr = (uint8_t)SvUV(ST(1))
;
	uint16_t	divider = (uint16_t)SvUV(ST(2))
;
    hipi_i2c_setSlaveAddress( baseaddress, addr );
    hipi_i2c_setClockDivider( baseaddress, divider );
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835__hipi_i2c_write); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835__hipi_i2c_write)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "baseaddress, buf, len");
    {
	volatile uint32_t*	baseaddress = INT2PTR(volatile uint32_t *,SvIV(ST(0)))
;
	const char*	buf = (const char *)SvPV_nolen(ST(1))
;
	uint32_t	len = (unsigned long)SvUV(ST(2))
;
	uint8_t	RETVAL;
	dXSTARG;
    RETVAL = hipi_i2c_write( baseaddress, buf, len );
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835__hipi_i2c_read); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835__hipi_i2c_read)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "baseaddress, buf, len");
    {
	volatile uint32_t*	baseaddress = INT2PTR(volatile uint32_t *,SvIV(ST(0)))
;
	char*	buf = (char *)SvPV_nolen(ST(1))
;
	uint32_t	len = (unsigned long)SvUV(ST(2))
;
	uint8_t	RETVAL;
	dXSTARG;
    RETVAL = hipi_i2c_read( baseaddress, buf, len );
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835__hipi_i2c_read_register); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835__hipi_i2c_read_register)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "baseaddress, regaddr, readbuf, len");
    {
	volatile uint32_t*	baseaddress = INT2PTR(volatile uint32_t *,SvIV(ST(0)))
;
	char*	regaddr = (char *)SvPV_nolen(ST(1))
;
	char*	readbuf = (char *)SvPV_nolen(ST(2))
;
	uint32_t	len = (unsigned long)SvUV(ST(3))
;
	uint8_t	RETVAL;
	dXSTARG;
    uint8_t reason = hipi_i2c_write( baseaddress, regaddr, 1 );
    if( reason )
    {
        RETVAL = reason;
    }
    else
    {
        RETVAL = hipi_i2c_read( baseaddress, readbuf, len );
    }
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835__hipi_i2c_read_register_rs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835__hipi_i2c_read_register_rs)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "baseaddress, regaddr, readbuf, len");
    {
	volatile uint32_t*	baseaddress = INT2PTR(volatile uint32_t *,SvIV(ST(0)))
;
	char*	regaddr = (char *)SvPV_nolen(ST(1))
;
	char*	readbuf = (char *)SvPV_nolen(ST(2))
;
	uint32_t	len = (unsigned long)SvUV(ST(3))
;
	uint8_t	RETVAL;
	dXSTARG;
    RETVAL = hipi_i2c_read_register_rs( baseaddress, regaddr, readbuf, len );
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835__hipi_bcm2835_init); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835__hipi_bcm2835_init)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
    RETVAL = bcm2835_init();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835__hipi_bcm2835_close); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835__hipi_bcm2835_close)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
    RETVAL = bcm2835_close();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_set_debug); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_set_debug)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "debug");
    {
	uint8_t	debug = (uint8_t)SvUV(ST(0))
;

	bcm2835_set_debug(debug);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_peri_read); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_peri_read)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "paddr");
    {
	uint32_t	RETVAL;
	dXSTARG;
	volatile uint32_t*	paddr = INT2PTR(volatile uint32_t *,SvIV(ST(0)))
;

	RETVAL = bcm2835_peri_read(paddr);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_peri_read_nb); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_peri_read_nb)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "paddr");
    {
	uint32_t	RETVAL;
	dXSTARG;
	volatile uint32_t*	paddr = INT2PTR(volatile uint32_t *,SvIV(ST(0)))
;

	RETVAL = bcm2835_peri_read_nb(paddr);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_peri_write); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_peri_write)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "paddr, value");
    {
	volatile uint32_t*	paddr = INT2PTR(volatile uint32_t *,SvIV(ST(0)))
;
	uint32_t	value = (unsigned long)SvUV(ST(1))
;

	bcm2835_peri_write(paddr, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_peri_write_nb); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_peri_write_nb)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "paddr, value");
    {
	volatile uint32_t*	paddr = INT2PTR(volatile uint32_t *,SvIV(ST(0)))
;
	uint32_t	value = (unsigned long)SvUV(ST(1))
;

	bcm2835_peri_write_nb(paddr, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_peri_set_bits); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_peri_set_bits)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "paddr, value, mask");
    {
	volatile uint32_t*	paddr = INT2PTR(volatile uint32_t *,SvIV(ST(0)))
;
	uint32_t	value = (unsigned long)SvUV(ST(1))
;
	uint32_t	mask = (unsigned long)SvUV(ST(2))
;

	bcm2835_peri_set_bits(paddr, value, mask);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_fsel); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_fsel)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, mode");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;
	uint8_t	mode = (uint8_t)SvUV(ST(1))
;

	bcm2835_gpio_fsel(pin, mode);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_set); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_set)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_set(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_clr(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_set_multi); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_set_multi)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "mask");
    {
	uint32_t	mask = (unsigned long)SvUV(ST(0))
;

	bcm2835_gpio_set_multi(mask);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr_multi); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr_multi)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "mask");
    {
	uint32_t	mask = (unsigned long)SvUV(ST(0))
;

	bcm2835_gpio_clr_multi(mask);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_lev); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_lev)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	RETVAL;
	dXSTARG;
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	RETVAL = bcm2835_gpio_lev(pin);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_eds); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_eds)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	RETVAL;
	dXSTARG;
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	RETVAL = bcm2835_gpio_eds(pin);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_set_eds); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_set_eds)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_set_eds(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_ren); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_ren)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_ren(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr_ren); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr_ren)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_clr_ren(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_fen); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_fen)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_fen(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr_fen); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr_fen)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_clr_fen(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_hen); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_hen)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_hen(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr_hen); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr_hen)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_clr_hen(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_len); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_len)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_len(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr_len); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr_len)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_clr_len(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_aren); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_aren)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_aren(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr_aren); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr_aren)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_clr_aren(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_afen); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_afen)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_afen(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr_afen); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_clr_afen)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_clr_afen(pin);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_pud); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_pud)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pud");
    {
	uint8_t	pud = (uint8_t)SvUV(ST(0))
;

	bcm2835_gpio_pud(pud);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_pudclk); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_pudclk)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, on");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;
	uint8_t	on = (uint8_t)SvUV(ST(1))
;

	bcm2835_gpio_pudclk(pin, on);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_pad); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_pad)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "group");
    {
	uint32_t	RETVAL;
	dXSTARG;
	uint8_t	group = (uint8_t)SvUV(ST(0))
;

	RETVAL = bcm2835_gpio_pad(group);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_set_pad); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_set_pad)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "group, control");
    {
	uint8_t	group = (uint8_t)SvUV(ST(0))
;
	uint32_t	control = (unsigned long)SvUV(ST(1))
;

	bcm2835_gpio_set_pad(group, control);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_delay); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_delay)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "millis");
    {
	unsigned int	millis = (unsigned int)SvUV(ST(0))
;

	bcm2835_delay(millis);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_delayMicroseconds); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_delayMicroseconds)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "micros");
    {
	uint64_t	micros = (uint64_t)SvUV(ST(0))
;

	bcm2835_delayMicroseconds(micros);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_write); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_write)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, on");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;
	uint8_t	on = (uint8_t)SvUV(ST(1))
;

	bcm2835_gpio_write(pin, on);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_write_multi); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_write_multi)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "mask, on");
    {
	uint32_t	mask = (unsigned long)SvUV(ST(0))
;
	uint8_t	on = (uint8_t)SvUV(ST(1))
;

	bcm2835_gpio_write_multi(mask, on);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_write_mask); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_write_mask)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "value, mask");
    {
	uint32_t	value = (unsigned long)SvUV(ST(0))
;
	uint32_t	mask = (unsigned long)SvUV(ST(1))
;

	bcm2835_gpio_write_mask(value, mask);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_set_pud); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_gpio_set_pud)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, pud");
    {
	uint8_t	pin = (uint8_t)SvUV(ST(0))
;
	uint8_t	pud = (uint8_t)SvUV(ST(1))
;

	bcm2835_gpio_set_pud(pin, pud);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_begin); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_begin)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	bcm2835_spi_begin();
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_end); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_end)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	bcm2835_spi_end();
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_setBitOrder); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_setBitOrder)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "order");
    {
	uint8_t	order = (uint8_t)SvUV(ST(0))
;

	bcm2835_spi_setBitOrder(order);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_setClockDivider); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_setClockDivider)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "divider");
    {
	uint16_t	divider = (uint16_t)SvUV(ST(0))
;

	bcm2835_spi_setClockDivider(divider);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_setDataMode); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_setDataMode)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "mode");
    {
	uint8_t	mode = (uint8_t)SvUV(ST(0))
;

	bcm2835_spi_setDataMode(mode);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_chipSelect); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_chipSelect)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cs");
    {
	uint8_t	cs = (uint8_t)SvUV(ST(0))
;

	bcm2835_spi_chipSelect(cs);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_setChipSelectPolarity); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_setChipSelectPolarity)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cs, active");
    {
	uint8_t	cs = (uint8_t)SvUV(ST(0))
;
	uint8_t	active = (uint8_t)SvUV(ST(1))
;

	bcm2835_spi_setChipSelectPolarity(cs, active);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_transfer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_transfer)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "value");
    {
	uint8_t	RETVAL;
	dXSTARG;
	uint8_t	value = (uint8_t)SvUV(ST(0))
;

	RETVAL = bcm2835_spi_transfer(value);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_hipi_spi_transfern); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_hipi_spi_transfern)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "tbuf");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV*	tbuf = ST(0)
;
    SV* rbuf = newSVsv(tbuf);
    bcm2835_spi_transfern( SvPVX(rbuf), (uint32_t)SvCUR(rbuf) );

    EXTEND(SP, 1);
    PUSHs(sv_2mortal(rbuf));
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_transfern); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_transfern)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "buf");
    {
	STRLEN	STRLEN_length_of_buf;
	short	XSauto_length_of_buf;
	char*	buf = (char *)SvPV(ST(0), STRLEN_length_of_buf);

	XSauto_length_of_buf = STRLEN_length_of_buf;

	bcm2835_spi_transfern(buf, XSauto_length_of_buf);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_hipi_spi_transfernb); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_hipi_spi_transfernb)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "tbuf");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV*	tbuf = ST(0)
;
    SV* rbuf = newSVsv(tbuf);
    bcm2835_spi_transfernb( SvPVX(tbuf), SvPVX(rbuf), (uint32_t)SvCUR(tbuf) );

    EXTEND(SP, 1);
    PUSHs(sv_2mortal(rbuf));
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_transfernb); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_transfernb)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "tbuf, rbuf");
    {
	STRLEN	STRLEN_length_of_tbuf;
	short	XSauto_length_of_tbuf;
	char*	tbuf = (char *)SvPV(ST(0), STRLEN_length_of_tbuf);
	char*	rbuf = (char *)SvPV_nolen(ST(1))
;

	XSauto_length_of_tbuf = STRLEN_length_of_tbuf;

	bcm2835_spi_transfernb(tbuf, rbuf, XSauto_length_of_tbuf);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_hipi_spi_writenb); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_hipi_spi_writenb)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "buf");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV*	buf = ST(0)
;
    SV* rbuf = sv_2mortal(newSVsv(buf));
    bcm2835_spi_writenb( SvPVX(rbuf), (uint32_t)SvCUR(rbuf) );

    EXTEND(SP, 1);
    PUSHs(rbuf);
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_writenb); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_spi_writenb)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "buf");
    {
	STRLEN	STRLEN_length_of_buf;
	short	XSauto_length_of_buf;
	char*	buf = (char *)SvPV(ST(0), STRLEN_length_of_buf);

	XSauto_length_of_buf = STRLEN_length_of_buf;

	bcm2835_spi_writenb(buf, XSauto_length_of_buf);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_begin); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_begin)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	bcm2835_i2c_begin();
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_end); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_end)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	bcm2835_i2c_end();
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_setSlaveAddress); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_setSlaveAddress)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "addr");
    {
	uint8_t	addr = (uint8_t)SvUV(ST(0))
;

	bcm2835_i2c_setSlaveAddress(addr);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_setClockDivider); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_setClockDivider)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "divider");
    {
	uint16_t	divider = (uint16_t)SvUV(ST(0))
;

	bcm2835_i2c_setClockDivider(divider);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_write); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_write)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "buf");
    {
	uint8_t	RETVAL;
	dXSTARG;
	STRLEN	STRLEN_length_of_buf;
	short	XSauto_length_of_buf;
	const char *	buf = (const char *)SvPV(ST(0), STRLEN_length_of_buf);

	XSauto_length_of_buf = STRLEN_length_of_buf;

	RETVAL = bcm2835_i2c_write(buf, XSauto_length_of_buf);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_read); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_read)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "buf, len");
    {
	uint8_t	RETVAL;
	dXSTARG;
	char*	buf = (char *)SvPV_nolen(ST(0))
;
	uint32_t	len = (unsigned long)SvUV(ST(1))
;

	RETVAL = bcm2835_i2c_read(buf, len);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_st_read); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_st_read)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	uint64_t	RETVAL;
	dXSTARG;

	RETVAL = bcm2835_st_read();
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_st_delay); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_st_delay)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "offset_micros, micros");
    {
	uint64_t	offset_micros = (uint64_t)SvUV(ST(0))
;
	uint64_t	micros = (uint64_t)SvUV(ST(1))
;

	bcm2835_st_delay(offset_micros, micros);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_set_baudrate); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_set_baudrate)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "baudrate");
    {
	uint32_t	baudrate = (unsigned long)SvUV(ST(0))
;

	bcm2835_i2c_set_baudrate(baudrate);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_read_register_rs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__BCM2835_bcm2835_i2c_read_register_rs)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "regaddr, buf, len");
    {
	uint8_t	RETVAL;
	dXSTARG;
	char*	regaddr = (char *)SvPV_nolen(ST(0))
;
	char*	buf = (char *)SvPV_nolen(ST(1))
;
	uint32_t	len = (unsigned long)SvUV(ST(2))
;

	RETVAL = bcm2835_i2c_read_register_rs(regaddr, buf, len);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_HiPi__BCM2835); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_HiPi__BCM2835)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("HiPi::BCM2835::bcm2835_gpio", XS_HiPi__BCM2835_bcm2835_gpio, file);
        newXS("HiPi::BCM2835::bcm2835_pwm", XS_HiPi__BCM2835_bcm2835_pwm, file);
        newXS("HiPi::BCM2835::bcm2835_clk", XS_HiPi__BCM2835_bcm2835_clk, file);
        newXS("HiPi::BCM2835::bcm2835_pads", XS_HiPi__BCM2835_bcm2835_pads, file);
        newXS("HiPi::BCM2835::bcm2835_spi0", XS_HiPi__BCM2835_bcm2835_spi0, file);
        newXS("HiPi::BCM2835::bcm2835_bsc0", XS_HiPi__BCM2835_bcm2835_bsc0, file);
        newXS("HiPi::BCM2835::bcm2835_bsc1", XS_HiPi__BCM2835_bcm2835_bsc1, file);
        newXS("HiPi::BCM2835::bcm2835_st", XS_HiPi__BCM2835_bcm2835_st, file);
        newXS("HiPi::BCM2835::hipi_gpio_fget", XS_HiPi__BCM2835_hipi_gpio_fget, file);
        newXS("HiPi::BCM2835::hipi_gpio_get_eds", XS_HiPi__BCM2835_hipi_gpio_get_eds, file);
        newXS("HiPi::BCM2835::_hipi_i2c_setSlaveAddress", XS_HiPi__BCM2835__hipi_i2c_setSlaveAddress, file);
        newXS("HiPi::BCM2835::_hipi_i2c_setClockDivider", XS_HiPi__BCM2835__hipi_i2c_setClockDivider, file);
        newXS("HiPi::BCM2835::_hipi_i2c_set_transfer_params", XS_HiPi__BCM2835__hipi_i2c_set_transfer_params, file);
        newXS("HiPi::BCM2835::_hipi_i2c_write", XS_HiPi__BCM2835__hipi_i2c_write, file);
        newXS("HiPi::BCM2835::_hipi_i2c_read", XS_HiPi__BCM2835__hipi_i2c_read, file);
        newXS("HiPi::BCM2835::_hipi_i2c_read_register", XS_HiPi__BCM2835__hipi_i2c_read_register, file);
        newXS("HiPi::BCM2835::_hipi_i2c_read_register_rs", XS_HiPi__BCM2835__hipi_i2c_read_register_rs, file);
        newXS("HiPi::BCM2835::_hipi_bcm2835_init", XS_HiPi__BCM2835__hipi_bcm2835_init, file);
        newXS("HiPi::BCM2835::_hipi_bcm2835_close", XS_HiPi__BCM2835__hipi_bcm2835_close, file);
        newXS("HiPi::BCM2835::bcm2835_set_debug", XS_HiPi__BCM2835_bcm2835_set_debug, file);
        newXS("HiPi::BCM2835::bcm2835_peri_read", XS_HiPi__BCM2835_bcm2835_peri_read, file);
        newXS("HiPi::BCM2835::bcm2835_peri_read_nb", XS_HiPi__BCM2835_bcm2835_peri_read_nb, file);
        newXS("HiPi::BCM2835::bcm2835_peri_write", XS_HiPi__BCM2835_bcm2835_peri_write, file);
        newXS("HiPi::BCM2835::bcm2835_peri_write_nb", XS_HiPi__BCM2835_bcm2835_peri_write_nb, file);
        newXS("HiPi::BCM2835::bcm2835_peri_set_bits", XS_HiPi__BCM2835_bcm2835_peri_set_bits, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_fsel", XS_HiPi__BCM2835_bcm2835_gpio_fsel, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_set", XS_HiPi__BCM2835_bcm2835_gpio_set, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_clr", XS_HiPi__BCM2835_bcm2835_gpio_clr, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_set_multi", XS_HiPi__BCM2835_bcm2835_gpio_set_multi, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_clr_multi", XS_HiPi__BCM2835_bcm2835_gpio_clr_multi, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_lev", XS_HiPi__BCM2835_bcm2835_gpio_lev, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_eds", XS_HiPi__BCM2835_bcm2835_gpio_eds, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_set_eds", XS_HiPi__BCM2835_bcm2835_gpio_set_eds, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_ren", XS_HiPi__BCM2835_bcm2835_gpio_ren, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_clr_ren", XS_HiPi__BCM2835_bcm2835_gpio_clr_ren, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_fen", XS_HiPi__BCM2835_bcm2835_gpio_fen, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_clr_fen", XS_HiPi__BCM2835_bcm2835_gpio_clr_fen, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_hen", XS_HiPi__BCM2835_bcm2835_gpio_hen, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_clr_hen", XS_HiPi__BCM2835_bcm2835_gpio_clr_hen, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_len", XS_HiPi__BCM2835_bcm2835_gpio_len, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_clr_len", XS_HiPi__BCM2835_bcm2835_gpio_clr_len, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_aren", XS_HiPi__BCM2835_bcm2835_gpio_aren, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_clr_aren", XS_HiPi__BCM2835_bcm2835_gpio_clr_aren, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_afen", XS_HiPi__BCM2835_bcm2835_gpio_afen, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_clr_afen", XS_HiPi__BCM2835_bcm2835_gpio_clr_afen, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_pud", XS_HiPi__BCM2835_bcm2835_gpio_pud, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_pudclk", XS_HiPi__BCM2835_bcm2835_gpio_pudclk, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_pad", XS_HiPi__BCM2835_bcm2835_gpio_pad, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_set_pad", XS_HiPi__BCM2835_bcm2835_gpio_set_pad, file);
        newXS("HiPi::BCM2835::bcm2835_delay", XS_HiPi__BCM2835_bcm2835_delay, file);
        newXS("HiPi::BCM2835::bcm2835_delayMicroseconds", XS_HiPi__BCM2835_bcm2835_delayMicroseconds, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_write", XS_HiPi__BCM2835_bcm2835_gpio_write, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_write_multi", XS_HiPi__BCM2835_bcm2835_gpio_write_multi, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_write_mask", XS_HiPi__BCM2835_bcm2835_gpio_write_mask, file);
        newXS("HiPi::BCM2835::bcm2835_gpio_set_pud", XS_HiPi__BCM2835_bcm2835_gpio_set_pud, file);
        newXS("HiPi::BCM2835::bcm2835_spi_begin", XS_HiPi__BCM2835_bcm2835_spi_begin, file);
        newXS("HiPi::BCM2835::bcm2835_spi_end", XS_HiPi__BCM2835_bcm2835_spi_end, file);
        newXS("HiPi::BCM2835::bcm2835_spi_setBitOrder", XS_HiPi__BCM2835_bcm2835_spi_setBitOrder, file);
        newXS("HiPi::BCM2835::bcm2835_spi_setClockDivider", XS_HiPi__BCM2835_bcm2835_spi_setClockDivider, file);
        newXS("HiPi::BCM2835::bcm2835_spi_setDataMode", XS_HiPi__BCM2835_bcm2835_spi_setDataMode, file);
        newXS("HiPi::BCM2835::bcm2835_spi_chipSelect", XS_HiPi__BCM2835_bcm2835_spi_chipSelect, file);
        newXS("HiPi::BCM2835::bcm2835_spi_setChipSelectPolarity", XS_HiPi__BCM2835_bcm2835_spi_setChipSelectPolarity, file);
        newXS("HiPi::BCM2835::bcm2835_spi_transfer", XS_HiPi__BCM2835_bcm2835_spi_transfer, file);
        newXS("HiPi::BCM2835::hipi_spi_transfern", XS_HiPi__BCM2835_hipi_spi_transfern, file);
        newXS("HiPi::BCM2835::bcm2835_spi_transfern", XS_HiPi__BCM2835_bcm2835_spi_transfern, file);
        newXS("HiPi::BCM2835::hipi_spi_transfernb", XS_HiPi__BCM2835_hipi_spi_transfernb, file);
        newXS("HiPi::BCM2835::bcm2835_spi_transfernb", XS_HiPi__BCM2835_bcm2835_spi_transfernb, file);
        newXS("HiPi::BCM2835::hipi_spi_writenb", XS_HiPi__BCM2835_hipi_spi_writenb, file);
        newXS("HiPi::BCM2835::bcm2835_spi_writenb", XS_HiPi__BCM2835_bcm2835_spi_writenb, file);
        newXS("HiPi::BCM2835::bcm2835_i2c_begin", XS_HiPi__BCM2835_bcm2835_i2c_begin, file);
        newXS("HiPi::BCM2835::bcm2835_i2c_end", XS_HiPi__BCM2835_bcm2835_i2c_end, file);
        newXS("HiPi::BCM2835::bcm2835_i2c_setSlaveAddress", XS_HiPi__BCM2835_bcm2835_i2c_setSlaveAddress, file);
        newXS("HiPi::BCM2835::bcm2835_i2c_setClockDivider", XS_HiPi__BCM2835_bcm2835_i2c_setClockDivider, file);
        newXS("HiPi::BCM2835::bcm2835_i2c_write", XS_HiPi__BCM2835_bcm2835_i2c_write, file);
        newXS("HiPi::BCM2835::bcm2835_i2c_read", XS_HiPi__BCM2835_bcm2835_i2c_read, file);
        newXS("HiPi::BCM2835::bcm2835_st_read", XS_HiPi__BCM2835_bcm2835_st_read, file);
        newXS("HiPi::BCM2835::bcm2835_st_delay", XS_HiPi__BCM2835_bcm2835_st_delay, file);
        newXS("HiPi::BCM2835::bcm2835_i2c_set_baudrate", XS_HiPi__BCM2835_bcm2835_i2c_set_baudrate, file);
        newXS("HiPi::BCM2835::bcm2835_i2c_read_register_rs", XS_HiPi__BCM2835_bcm2835_i2c_read_register_rs, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

