/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of Wiring.xs. Do not edit this file, edit Wiring.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

///////////////////////////////////////////////////////////////////////////////////////
// File          wiring/Wiring.xs
// Description:  XS module for MyPi::Wiring
// Created       Fri Nov 23 12:13:43 2012
// SVN Id        $Id:$
// Copyright:    Copyright (c) 2012 Mark Dootson
// Licence:      This work is free software; you can redistribute it and/or modify it 
//               under the terms of the GNU General Public License as published by the 
//               Free Software Foundation; either version 3 of the License, or any later 
//               version.
///////////////////////////////////////////////////////////////////////////////////////

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "mylib/include/ppport.h"
#include "Wiring/src/wiringPi/wiringPi.h"
#include "Wiring/src/wiringPi/wiringSerial.h"
#include "Wiring/src/wiringPi/wiringShift.h"
#include "Wiring/src/wiringPi/gertboard.h"
#include "Wiring/src/wiringPi/piNes.h"
#include "Wiring/src/wiringPi/softPwm.h"
#include "Wiring/src/wiringPi/softServo.h"
#include "Wiring/src/wiringPi/softTone.h"
#include "Wiring/src/wiringPi/lcd.h"
#include "Wiring/src/wiringPi/wiringPiSPI.h"
#include "Wiring/src/wiringPi/wiringPiI2C.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */


XS_EUPXS(XS_HiPi__Wiring_wiringPiSetup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiSetup)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSetup();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_wiringPiSetupSys); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiSetupSys)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSetupSys();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_wiringPiSetupGpio); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiSetupGpio)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSetupGpio();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_wiringPiSetupPiFace); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiSetupPiFace)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSetupPiFace();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_piBoardRev); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_piBoardRev)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = piBoardRev();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_wpiPinToGpio); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wpiPinToGpio)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "wpiPin");
    {
	int	wpiPin = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = wpiPinToGpio(wpiPin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_wiringPiSetupPiFaceForGpioProg); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiSetupPiFaceForGpioProg)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSetupPiFaceForGpioProg();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_pinMode); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_pinMode)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, mode");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	mode = (int)SvIV(ST(1))
;

	pinMode(pin, mode);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_pullUpDnControl); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_pullUpDnControl)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, pud");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	pud = (int)SvIV(ST(1))
;

	pullUpDnControl(pin, pud);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_digitalWrite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_digitalWrite)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, value");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	value = (int)SvIV(ST(1))
;

	digitalWrite(pin, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_digitalWriteByte); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_digitalWriteByte)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "value");
    {
	int	value = (int)SvIV(ST(0))
;

	digitalWriteByte(value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_pwmWrite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_pwmWrite)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, value");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	value = (int)SvIV(ST(1))
;

	pwmWrite(pin, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_setPadDrive); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_setPadDrive)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "group, value");
    {
	int	group = (int)SvIV(ST(0))
;
	int	value = (int)SvIV(ST(1))
;

	setPadDrive(group, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_digitalRead); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_digitalRead)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = digitalRead(pin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_delayMicroseconds); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_delayMicroseconds)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "howLong");
    {
	unsigned int	howLong = (unsigned int)SvUV(ST(0))
;

	delayMicroseconds(howLong);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_pwmSetMode); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_pwmSetMode)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "mode");
    {
	int	mode = (int)SvIV(ST(0))
;

	pwmSetMode(mode);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_pwmSetRange); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_pwmSetRange)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "range");
    {
	unsigned int	range = (unsigned int)SvUV(ST(0))
;

	pwmSetRange(range);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_pwmSetClock); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_pwmSetClock)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "divisor");
    {
	int	divisor = (int)SvIV(ST(0))
;

	pwmSetClock(divisor);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_waitForInterrupt); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_waitForInterrupt)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, mS");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	mS = (int)SvIV(ST(1))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = waitForInterrupt(pin, mS);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_piLock); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_piLock)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "key");
    {
	int	key = (int)SvIV(ST(0))
;

	piLock(key);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_piUnlock); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_piUnlock)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "key");
    {
	int	key = (int)SvIV(ST(0))
;

	piUnlock(key);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_piHiPri); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_piHiPri)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pri");
    {
	int	pri = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = piHiPri(pri);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_delay); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_delay)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "howLong");
    {
	unsigned int	howLong = (unsigned int)SvUV(ST(0))
;

	delay(howLong);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_millis); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_millis)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	unsigned int	RETVAL;
	dXSTARG;

	RETVAL = millis();
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_gertboardAnalogWrite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_gertboardAnalogWrite)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "chan, value");
    {
	int	chan = (int)SvIV(ST(0))
;
	int	value = (int)SvIV(ST(1))
;

	gertboardAnalogWrite(chan, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_gertboardAnalogRead); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_gertboardAnalogRead)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "chan");
    {
	int	chan = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = gertboardAnalogRead(chan);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_gertboardSPISetup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_gertboardSPISetup)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = gertboardSPISetup();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_lcdHome); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_lcdHome)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0))
;

	lcdHome(fd);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_lcdClear); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_lcdClear)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0))
;

	lcdClear(fd);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_lcdPosition); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_lcdPosition)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "fd, x, y");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	x = (int)SvIV(ST(1))
;
	int	y = (int)SvIV(ST(2))
;

	lcdPosition(fd, x, y);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_lcdPutchar); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_lcdPutchar)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, data");
    {
	int	fd = (int)SvIV(ST(0))
;
	uint8_t	data = (uint8_t)SvUV(ST(1))
;

	lcdPutchar(fd, data);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_lcdPuts); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_lcdPuts)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, putstring");
    {
	int	fd = (int)SvIV(ST(0))
;
	char*	putstring = (char *)SvPV_nolen(ST(1))
;

	lcdPuts(fd, putstring);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_lcdInit); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_lcdInit)
{
    dVAR; dXSARGS;
    if (items != 13)
       croak_xs_usage(cv,  "rows, cols, bits, rs, strb, d0, d1, d2, d3, d4, d5, d6, d7");
    {
	int	rows = (int)SvIV(ST(0))
;
	int	cols = (int)SvIV(ST(1))
;
	int	bits = (int)SvIV(ST(2))
;
	int	rs = (int)SvIV(ST(3))
;
	int	strb = (int)SvIV(ST(4))
;
	int	d0 = (int)SvIV(ST(5))
;
	int	d1 = (int)SvIV(ST(6))
;
	int	d2 = (int)SvIV(ST(7))
;
	int	d3 = (int)SvIV(ST(8))
;
	int	d4 = (int)SvIV(ST(9))
;
	int	d5 = (int)SvIV(ST(10))
;
	int	d6 = (int)SvIV(ST(11))
;
	int	d7 = (int)SvIV(ST(12))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = lcdInit(rows, cols, bits, rs, strb, d0, d1, d2, d3, d4, d5, d6, d7);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_setupNesJoystick); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_setupNesJoystick)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "dPin, cPin, lPin");
    {
	int	dPin = (int)SvIV(ST(0))
;
	int	cPin = (int)SvIV(ST(1))
;
	int	lPin = (int)SvIV(ST(2))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = setupNesJoystick(dPin, cPin, lPin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_readNesJoystick); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_readNesJoystick)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "joystick");
    {
	int	joystick = (int)SvIV(ST(0))
;
	unsigned int	RETVAL;
	dXSTARG;

	RETVAL = readNesJoystick(joystick);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_softPwmCreate); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_softPwmCreate)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "pin, value, range");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	value = (int)SvIV(ST(1))
;
	int	range = (int)SvIV(ST(2))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = softPwmCreate(pin, value, range);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_softPwmWrite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_softPwmWrite)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, value");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	value = (int)SvIV(ST(1))
;

	softPwmWrite(pin, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_softServoWrite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_softServoWrite)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, value");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	value = (int)SvIV(ST(1))
;

	softServoWrite(pin, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_softServoSetup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_softServoSetup)
{
    dVAR; dXSARGS;
    if (items != 8)
       croak_xs_usage(cv,  "p0, p1, p2, p3, p4, p5, p6, p7");
    {
	int	p0 = (int)SvIV(ST(0))
;
	int	p1 = (int)SvIV(ST(1))
;
	int	p2 = (int)SvIV(ST(2))
;
	int	p3 = (int)SvIV(ST(3))
;
	int	p4 = (int)SvIV(ST(4))
;
	int	p5 = (int)SvIV(ST(5))
;
	int	p6 = (int)SvIV(ST(6))
;
	int	p7 = (int)SvIV(ST(7))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = softServoSetup(p0, p1, p2, p3, p4, p5, p6, p7);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_softToneCreate); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_softToneCreate)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = softToneCreate(pin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_softToneWrite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_softToneWrite)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, frewq");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	frewq = (int)SvIV(ST(1))
;

	softToneWrite(pin, frewq);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_wiringPiI2CRead); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiI2CRead)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiI2CRead(fd);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_wiringPiI2CReadReg8); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiI2CReadReg8)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, reg");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	reg = (int)SvIV(ST(1))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiI2CReadReg8(fd, reg);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_wiringPiI2CReadReg16); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiI2CReadReg16)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, reg");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	reg = (int)SvIV(ST(1))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiI2CReadReg16(fd, reg);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_wiringPiI2CWrite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiI2CWrite)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, data");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	data = (int)SvIV(ST(1))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiI2CWrite(fd, data);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_wiringPiI2CWriteReg8); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiI2CWriteReg8)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "fd, reg, data");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	reg = (int)SvIV(ST(1))
;
	int	data = (int)SvIV(ST(2))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiI2CWriteReg8(fd, reg, data);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_wiringPiI2CWriteReg16); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiI2CWriteReg16)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "fd, reg, data");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	reg = (int)SvIV(ST(1))
;
	int	data = (int)SvIV(ST(2))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiI2CWriteReg16(fd, reg, data);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_wiringPiI2CSetup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiI2CSetup)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "devId");
    {
	int	devId = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiI2CSetup(devId);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_wiringPiSPIGetFd); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiSPIGetFd)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "channel");
    {
	int	channel = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSPIGetFd(channel);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_wiringPiSPIDataRW); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiSPIDataRW)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "channel, data, len");
    {
	int	channel = (int)SvIV(ST(0))
;
	unsigned char*	data = (unsigned char *)SvPV_nolen(ST(1))
;
	int	len = (int)SvIV(ST(2))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSPIDataRW(channel, data, len);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_wiringPiSPISetup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_wiringPiSPISetup)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "channel, speed");
    {
	int	channel = (int)SvIV(ST(0))
;
	int	speed = (int)SvIV(ST(1))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSPISetup(channel, speed);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_serialOpen); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_serialOpen)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "device, baud");
    {
	char*	device = (char *)SvPV_nolen(ST(0))
;
	int	baud = (int)SvIV(ST(1))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = serialOpen(device, baud);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_serialClose); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_serialClose)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0))
;

	serialClose(fd);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_serialFlush); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_serialFlush)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0))
;

	serialFlush(fd);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_serialPutchar); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_serialPutchar)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, c");
    {
	int	fd = (int)SvIV(ST(0))
;
	unsigned char	c = (unsigned char)SvUV(ST(1))
;

	serialPutchar(fd, c);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_serialPuts); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_serialPuts)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, s");
    {
	int	fd = (int)SvIV(ST(0))
;
	char*	s = (char *)SvPV_nolen(ST(1))
;

	serialPuts(fd, s);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_HiPi__Wiring_serialDataAvail); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_serialDataAvail)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = serialDataAvail(fd);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_serialGetchar); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_serialGetchar)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = serialGetchar(fd);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_shiftIn); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_shiftIn)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "dPin, cPin, order");
    {
	uint8_t	dPin = (uint8_t)SvUV(ST(0))
;
	uint8_t	cPin = (uint8_t)SvUV(ST(1))
;
	uint8_t	order = (uint8_t)SvUV(ST(2))
;
	uint8_t	RETVAL;
	dXSTARG;

	RETVAL = shiftIn(dPin, cPin, order);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Wiring_shiftOut); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Wiring_shiftOut)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "dPin, cPin, order, val");
    {
	uint8_t	dPin = (uint8_t)SvUV(ST(0))
;
	uint8_t	cPin = (uint8_t)SvUV(ST(1))
;
	uint8_t	order = (uint8_t)SvUV(ST(2))
;
	uint8_t	val = (uint8_t)SvUV(ST(3))
;

	shiftOut(dPin, cPin, order, val);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_HiPi__Wiring); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_HiPi__Wiring)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("HiPi::Wiring::wiringPiSetup", XS_HiPi__Wiring_wiringPiSetup, file);
        newXS("HiPi::Wiring::wiringPiSetupSys", XS_HiPi__Wiring_wiringPiSetupSys, file);
        newXS("HiPi::Wiring::wiringPiSetupGpio", XS_HiPi__Wiring_wiringPiSetupGpio, file);
        newXS("HiPi::Wiring::wiringPiSetupPiFace", XS_HiPi__Wiring_wiringPiSetupPiFace, file);
        newXS("HiPi::Wiring::piBoardRev", XS_HiPi__Wiring_piBoardRev, file);
        newXS("HiPi::Wiring::wpiPinToGpio", XS_HiPi__Wiring_wpiPinToGpio, file);
        newXS("HiPi::Wiring::wiringPiSetupPiFaceForGpioProg", XS_HiPi__Wiring_wiringPiSetupPiFaceForGpioProg, file);
        newXS("HiPi::Wiring::pinMode", XS_HiPi__Wiring_pinMode, file);
        newXS("HiPi::Wiring::pullUpDnControl", XS_HiPi__Wiring_pullUpDnControl, file);
        newXS("HiPi::Wiring::digitalWrite", XS_HiPi__Wiring_digitalWrite, file);
        newXS("HiPi::Wiring::digitalWriteByte", XS_HiPi__Wiring_digitalWriteByte, file);
        newXS("HiPi::Wiring::pwmWrite", XS_HiPi__Wiring_pwmWrite, file);
        newXS("HiPi::Wiring::setPadDrive", XS_HiPi__Wiring_setPadDrive, file);
        newXS("HiPi::Wiring::digitalRead", XS_HiPi__Wiring_digitalRead, file);
        newXS("HiPi::Wiring::delayMicroseconds", XS_HiPi__Wiring_delayMicroseconds, file);
        newXS("HiPi::Wiring::pwmSetMode", XS_HiPi__Wiring_pwmSetMode, file);
        newXS("HiPi::Wiring::pwmSetRange", XS_HiPi__Wiring_pwmSetRange, file);
        newXS("HiPi::Wiring::pwmSetClock", XS_HiPi__Wiring_pwmSetClock, file);
        newXS("HiPi::Wiring::waitForInterrupt", XS_HiPi__Wiring_waitForInterrupt, file);
        newXS("HiPi::Wiring::piLock", XS_HiPi__Wiring_piLock, file);
        newXS("HiPi::Wiring::piUnlock", XS_HiPi__Wiring_piUnlock, file);
        newXS("HiPi::Wiring::piHiPri", XS_HiPi__Wiring_piHiPri, file);
        newXS("HiPi::Wiring::delay", XS_HiPi__Wiring_delay, file);
        newXS("HiPi::Wiring::millis", XS_HiPi__Wiring_millis, file);
        newXS("HiPi::Wiring::gertboardAnalogWrite", XS_HiPi__Wiring_gertboardAnalogWrite, file);
        newXS("HiPi::Wiring::gertboardAnalogRead", XS_HiPi__Wiring_gertboardAnalogRead, file);
        newXS("HiPi::Wiring::gertboardSPISetup", XS_HiPi__Wiring_gertboardSPISetup, file);
        newXS("HiPi::Wiring::lcdHome", XS_HiPi__Wiring_lcdHome, file);
        newXS("HiPi::Wiring::lcdClear", XS_HiPi__Wiring_lcdClear, file);
        newXS("HiPi::Wiring::lcdPosition", XS_HiPi__Wiring_lcdPosition, file);
        newXS("HiPi::Wiring::lcdPutchar", XS_HiPi__Wiring_lcdPutchar, file);
        newXS("HiPi::Wiring::lcdPuts", XS_HiPi__Wiring_lcdPuts, file);
        newXS("HiPi::Wiring::lcdInit", XS_HiPi__Wiring_lcdInit, file);
        newXS("HiPi::Wiring::setupNesJoystick", XS_HiPi__Wiring_setupNesJoystick, file);
        newXS("HiPi::Wiring::readNesJoystick", XS_HiPi__Wiring_readNesJoystick, file);
        newXS("HiPi::Wiring::softPwmCreate", XS_HiPi__Wiring_softPwmCreate, file);
        newXS("HiPi::Wiring::softPwmWrite", XS_HiPi__Wiring_softPwmWrite, file);
        newXS("HiPi::Wiring::softServoWrite", XS_HiPi__Wiring_softServoWrite, file);
        newXS("HiPi::Wiring::softServoSetup", XS_HiPi__Wiring_softServoSetup, file);
        newXS("HiPi::Wiring::softToneCreate", XS_HiPi__Wiring_softToneCreate, file);
        newXS("HiPi::Wiring::softToneWrite", XS_HiPi__Wiring_softToneWrite, file);
        newXS("HiPi::Wiring::wiringPiI2CRead", XS_HiPi__Wiring_wiringPiI2CRead, file);
        newXS("HiPi::Wiring::wiringPiI2CReadReg8", XS_HiPi__Wiring_wiringPiI2CReadReg8, file);
        newXS("HiPi::Wiring::wiringPiI2CReadReg16", XS_HiPi__Wiring_wiringPiI2CReadReg16, file);
        newXS("HiPi::Wiring::wiringPiI2CWrite", XS_HiPi__Wiring_wiringPiI2CWrite, file);
        newXS("HiPi::Wiring::wiringPiI2CWriteReg8", XS_HiPi__Wiring_wiringPiI2CWriteReg8, file);
        newXS("HiPi::Wiring::wiringPiI2CWriteReg16", XS_HiPi__Wiring_wiringPiI2CWriteReg16, file);
        newXS("HiPi::Wiring::wiringPiI2CSetup", XS_HiPi__Wiring_wiringPiI2CSetup, file);
        newXS("HiPi::Wiring::wiringPiSPIGetFd", XS_HiPi__Wiring_wiringPiSPIGetFd, file);
        newXS("HiPi::Wiring::wiringPiSPIDataRW", XS_HiPi__Wiring_wiringPiSPIDataRW, file);
        newXS("HiPi::Wiring::wiringPiSPISetup", XS_HiPi__Wiring_wiringPiSPISetup, file);
        newXS("HiPi::Wiring::serialOpen", XS_HiPi__Wiring_serialOpen, file);
        newXS("HiPi::Wiring::serialClose", XS_HiPi__Wiring_serialClose, file);
        newXS("HiPi::Wiring::serialFlush", XS_HiPi__Wiring_serialFlush, file);
        newXS("HiPi::Wiring::serialPutchar", XS_HiPi__Wiring_serialPutchar, file);
        newXS("HiPi::Wiring::serialPuts", XS_HiPi__Wiring_serialPuts, file);
        newXS("HiPi::Wiring::serialDataAvail", XS_HiPi__Wiring_serialDataAvail, file);
        newXS("HiPi::Wiring::serialGetchar", XS_HiPi__Wiring_serialGetchar, file);
        newXS("HiPi::Wiring::shiftIn", XS_HiPi__Wiring_shiftIn, file);
        newXS("HiPi::Wiring::shiftOut", XS_HiPi__Wiring_shiftOut, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

